/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "telemetry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(spextro_Telemetry, spextro_Telemetry, AUTO)


PB_BIND(spextro_Telemetry_Header, spextro_Telemetry_Header, AUTO)


PB_BIND(spextro_Telemetry_Altitude, spextro_Telemetry_Altitude, AUTO)


PB_BIND(spextro_Telemetry_Environmental, spextro_Telemetry_Environmental, AUTO)


PB_BIND(spextro_Telemetry_Orientation, spextro_Telemetry_Orientation, AUTO)


PB_BIND(spextro_Telemetry_GPSPosition, spextro_Telemetry_GPSPosition, AUTO)


PB_BIND(spextro_Telemetry_SciencePayload, spextro_Telemetry_SciencePayload, AUTO)


PB_BIND(spextro_Telemetry_Acceleration, spextro_Telemetry_Acceleration, AUTO)


PB_BIND(spextro_Telemetry_SystemHealth, spextro_Telemetry_SystemHealth, AUTO)


PB_BIND(spextro_Telemetry_SystemPhase, spextro_Telemetry_SystemPhase, AUTO)


PB_BIND(spextro_Telemetry_DeploymentSwitchERROR, spextro_Telemetry_DeploymentSwitchERROR, AUTO)


PB_BIND(spextro_Telemetry_PowerERROR, spextro_Telemetry_PowerERROR, AUTO)


PB_BIND(spextro_Telemetry_StorageERROR, spextro_Telemetry_StorageERROR, AUTO)


PB_BIND(spextro_Telemetry_HardwareERROR, spextro_Telemetry_HardwareERROR, AUTO)







